[0m23:58:38.562707 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8371a08250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8372f27be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8372f27b80>]}


============================== 23:58:38.566454 | 95807d7c-3853-4a38-bf47-b8a7540fc106 ==============================
[0m23:58:38.566454 [info ] [MainThread]: Running with dbt=1.5.0
[0m23:58:38.566929 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/eyaldiamant/opt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:58:38.567702 [error] [MainThread]: Encountered an error:
1
[0m23:58:38.568388 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/task/init.py", line 285, in run
    sys.exit(1)
SystemExit: 1

[0m23:58:38.569120 [debug] [MainThread]: Command `dbt init` failed at 23:58:38.568831 after 0.06 seconds
[0m23:58:38.569390 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8371a08250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8372f39b20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8372f39c70>]}
[0m23:58:38.569649 [debug] [MainThread]: Flushing usage events
[0m23:59:51.475779 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa549ab8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa54afe8bb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa54afe8b50>]}


============================== 23:59:51.479209 | 0c00a456-8baf-4dbe-b4b9-91ef15a01166 ==============================
[0m23:59:51.479209 [info ] [MainThread]: Running with dbt=1.5.0
[0m23:59:51.479663 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/eyaldiamant/opt/anaconda3/lib/python3.9', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m23:59:51.480360 [error] [MainThread]: Encountered an error:
1
[0m23:59:51.480998 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/task/init.py", line 285, in run
    sys.exit(1)
SystemExit: 1

[0m23:59:51.481695 [debug] [MainThread]: Command `dbt init` failed at 23:59:51.481427 after 0.02 seconds
[0m23:59:51.481940 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa549ab8790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa54affdaf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa54affdc40>]}
[0m23:59:51.482172 [debug] [MainThread]: Flushing usage events
[0m00:02:55.652103 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc941b08760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc942908b50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc942908ac0>]}


============================== 00:02:55.655503 | 9323a97a-e36b-4503-ab93-b3d3b3f65cc6 ==============================
[0m00:02:55.655503 [info ] [MainThread]: Running with dbt=1.5.0
[0m00:02:55.655937 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/eyaldiamant/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m00:02:55.656406 [warn ] [MainThread]: [OpenCommand]: Unable to parse dict {'open_cmd': 'open', 'profiles_dir': PosixPath('/Users/eyaldiamant/.dbt')}
[0m00:02:55.656656 [info ] [MainThread]: To view your profiles.yml file, run:

 
[0m00:02:55.657367 [debug] [MainThread]: Command `dbt debug` succeeded at 00:02:55.657022 after 0.02 seconds
[0m00:02:55.657604 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc941b08760>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc94292f9d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fc94292f820>]}
[0m00:02:55.657837 [debug] [MainThread]: Flushing usage events
[0m00:08:11.752528 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e9af8250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1eb027be0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1eb027b80>]}


============================== 00:08:11.755950 | 243e7e1f-baeb-4b04-b63c-fce96e98d994 ==============================
[0m00:08:11.755950 [info ] [MainThread]: Running with dbt=1.5.0
[0m00:08:11.756397 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m00:08:11.757114 [error] [MainThread]: Encountered an error:
1
[0m00:08:11.757765 [error] [MainThread]: Traceback (most recent call last):
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 86, in wrapper
    result, success = func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/requires.py", line 71, in wrapper
    return func(*args, **kwargs)
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/cli/main.py", line 459, in init
    results = task.run()
  File "/Users/eyaldiamant/opt/anaconda3/lib/python3.9/site-packages/dbt/task/init.py", line 285, in run
    sys.exit(1)
SystemExit: 1

[0m00:08:11.758464 [debug] [MainThread]: Command `dbt init` failed at 00:08:11.758195 after 0.02 seconds
[0m00:08:11.758701 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1e9af8250>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1eb03ab20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa1eb03ac70>]}
[0m00:08:11.758937 [debug] [MainThread]: Flushing usage events
[0m09:31:37.642971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95f9afc340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95fb047310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95fb0473a0>]}


============================== 09:31:37.646741 | aeda85c4-2379-4715-884f-9a14126fa8f7 ==============================
[0m09:31:37.646741 [info ] [MainThread]: Running with dbt=1.5.0
[0m09:31:37.647210 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/eyaldiamant/Desktop/dbt_course/dbt_course_public', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m09:31:37.647680 [warn ] [MainThread]: [OpenCommand]: Unable to parse dict {'open_cmd': 'open', 'profiles_dir': PosixPath('/Users/eyaldiamant/Desktop/dbt_course/dbt_course_public')}
[0m09:31:37.647925 [info ] [MainThread]: To view your profiles.yml file, run:

 
[0m09:31:37.648658 [debug] [MainThread]: Command `dbt debug` succeeded at 09:31:37.648323 after 0.03 seconds
[0m09:31:37.648898 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95f9afc340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95e81168e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f95fb0477c0>]}
[0m09:31:37.649135 [debug] [MainThread]: Flushing usage events
[0m11:04:12.957958 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92d9adb190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92dac87340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92dac87370>]}


============================== 11:04:12.961824 | 96b39dbd-b249-4301-a708-bde029a667e1 ==============================
[0m11:04:12.961824 [info ] [MainThread]: Running with dbt=1.5.0
[0m11:04:12.962325 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/eyaldiamant/Desktop/dbt_course/dbt_course_public', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True'}
[0m11:04:12.962794 [info ] [MainThread]: dbt version: 1.5.0
[0m11:04:12.963041 [info ] [MainThread]: python version: 3.9.13
[0m11:04:12.963266 [info ] [MainThread]: python path: /Users/eyaldiamant/opt/anaconda3/bin/python
[0m11:04:12.963485 [info ] [MainThread]: os info: macOS-10.16-x86_64-i386-64bit
[0m11:04:12.963705 [info ] [MainThread]: Using profiles.yml file at /Users/eyaldiamant/Desktop/dbt_course/dbt_course_public/profiles.yml
[0m11:04:12.963923 [info ] [MainThread]: Using dbt_project.yml file at /Users/eyaldiamant/Desktop/dbt_course/dbt_course_public/dbt_project.yml
[0m11:04:12.964135 [info ] [MainThread]: Configuration:
[0m11:04:15.276344 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m11:04:15.276716 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m11:04:15.276959 [info ] [MainThread]: Required dependencies:
[0m11:04:15.277262 [debug] [MainThread]: Executing "git --help"
[0m11:04:15.570366 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m11:04:15.571255 [debug] [MainThread]: STDERR: "b''"
[0m11:04:15.571543 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m11:04:15.571831 [info ] [MainThread]: Connection:
[0m11:04:15.572181 [info ] [MainThread]:   account: dw24986.europe-west2.gcp
[0m11:04:15.572430 [info ] [MainThread]:   user: ediamant
[0m11:04:15.572644 [info ] [MainThread]:   database: PSHITA
[0m11:04:15.572851 [info ] [MainThread]:   schema: APP
[0m11:04:15.573062 [info ] [MainThread]:   warehouse: INGESTION_WH
[0m11:04:15.573268 [info ] [MainThread]:   role: sysadmin
[0m11:04:15.573477 [info ] [MainThread]:   client_session_keep_alive: False
[0m11:04:15.573693 [info ] [MainThread]:   query_tag: None
[0m11:04:15.604865 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m11:04:15.607760 [debug] [MainThread]: Using snowflake connection "debug"
[0m11:04:15.608351 [debug] [MainThread]: On debug: select 1 as id
[0m11:04:15.608728 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:04:21.928098 [debug] [MainThread]: SQL status: SUCCESS 1 in 6.0 seconds
[0m11:04:21.932494 [debug] [MainThread]: On debug: Close
[0m11:04:22.453033 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m11:04:22.455042 [info ] [MainThread]: [31m1 check failed:[0m
[0m11:04:22.456130 [info ] [MainThread]: Could not load dbt_project.yml

[0m11:04:22.458474 [debug] [MainThread]: Command `dbt debug` failed at 11:04:22.457589 after 9.52 seconds
[0m11:04:22.459317 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m11:04:22.460084 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92d9adb190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92e8473310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f92e8804bb0>]}
[0m11:04:22.460937 [debug] [MainThread]: Flushing usage events
